### ISSUE TITLE
[Bug] Remaining Checklist for WebUI Settings

### ISSUE THREAD

**Issue by godver3** [godver3/cli_debrid#117]
- [x] Trakt Authorization
- [x] Versions nested/paired lists
- [x] Content Sources checkboxes for Versions
- [x] Debug Setting API Key
- [x] Toggles only working after refresh (Content Source only?)
- [x] Scrapers not saving
- [x] Content Sources Schema
